
#include "types.h"
#include "render.h"
#include "mappings.h"


const TextureMapping *Mappings::default_texture_map() {
    static const TextureMapping texture_map = {
        { Tile::BORDER_N,    { 0, 9 } },
        { Tile::BORDER_S,    { 1, 9 } },
        { Tile::BORDER_E,    { 2, 9 } },
        { Tile::BORDER_W,    { 3, 9 } },
        { Tile::BORDER_NW,   { 1, 7 } },
        { Tile::BORDER_NE,   { 0, 7 } },
        { Tile::BORDER_SW,   { 1, 6 } },
        { Tile::BORDER_SE,   { 0, 6 } },
        { Tile::BORDER_NS,   { 0, 8 } },
        { Tile::BORDER_WE,   { 1, 8 } },
        { Tile::BORDER_NSW,  { 3, 6 } },
        { Tile::BORDER_NSE,  { 2, 7 } },
        { Tile::BORDER_SWE,  { 2, 6 } },
        { Tile::BORDER_NWE,  { 3, 7 } },
        { Tile::BORDER_NSWE, { 3, 8 } },
        { Tile::BORDER_NONE, { 2, 8 } },
    
        { Tile::BORDER_N_BOLD,    { 4, 9 } },
        { Tile::BORDER_S_BOLD,    { 5, 9 } },
        { Tile::BORDER_E_BOLD,    { 6, 9 } },
        { Tile::BORDER_W_BOLD,    { 7, 9 } },
        { Tile::BORDER_NW_BOLD,   { 5, 7 } },
        { Tile::BORDER_NE_BOLD,   { 4, 7 } },
        { Tile::BORDER_SW_BOLD,   { 5, 6 } },
        { Tile::BORDER_SE_BOLD,   { 4, 6 } },
        { Tile::BORDER_NS_BOLD,   { 4, 8 } },
        { Tile::BORDER_WE_BOLD,   { 5, 8 } },
        { Tile::BORDER_NSW_BOLD,  { 7, 6 } },
        { Tile::BORDER_NSE_BOLD,  { 6, 7 } },
        { Tile::BORDER_SWE_BOLD,  { 6, 6 } },
        { Tile::BORDER_NWE_BOLD,  { 7, 7 } },
        { Tile::BORDER_NSWE_BOLD, { 7, 8 } },
        { Tile::BORDER_NONE_BOLD, { 6, 8 } },
    
        { Tile::BORDER_ROUND_N,    {  8, 9 } },
        { Tile::BORDER_ROUND_S,    {  9, 9 } },
        { Tile::BORDER_ROUND_E,    { 10, 9 } },
        { Tile::BORDER_ROUND_W,    { 11, 9 } },
        { Tile::BORDER_ROUND_NW,   {  9, 7 } },
        { Tile::BORDER_ROUND_NE,   {  8, 7 } },
        { Tile::BORDER_ROUND_SW,   {  9, 6 } },
        { Tile::BORDER_ROUND_SE,   {  8, 6 } },
        { Tile::BORDER_ROUND_NS,   {  8, 8 } },
        { Tile::BORDER_ROUND_WE,   {  9, 8 } },
        { Tile::BORDER_ROUND_NSW,  { 11, 6 } },
        { Tile::BORDER_ROUND_NSE,  { 10, 7 } },
        { Tile::BORDER_ROUND_SWE,  { 10, 6 } },
        { Tile::BORDER_ROUND_NWE,  { 11, 7 } },
        { Tile::BORDER_ROUND_NSWE, { 11, 8 } },
        { Tile::BORDER_ROUND_NONE, { 10, 8 } },
    
        { Tile::BORDER_ROUND_N_BOLD,    { 12, 9 } },
        { Tile::BORDER_ROUND_S_BOLD,    { 13, 9 } },
        { Tile::BORDER_ROUND_E_BOLD,    { 14, 9 } },
        { Tile::BORDER_ROUND_W_BOLD,    { 15, 9 } },
        { Tile::BORDER_ROUND_NW_BOLD,   { 13, 7 } },
        { Tile::BORDER_ROUND_NE_BOLD,   { 12, 7 } },
        { Tile::BORDER_ROUND_SW_BOLD,   { 13, 6 } },
        { Tile::BORDER_ROUND_SE_BOLD,   { 12, 6 } },
        { Tile::BORDER_ROUND_NS_BOLD,   { 12, 8 } },
        { Tile::BORDER_ROUND_WE_BOLD,   { 13, 8 } },
        { Tile::BORDER_ROUND_NSW_BOLD,  { 15, 6 } },
        { Tile::BORDER_ROUND_NSE_BOLD,  { 14, 7 } },
        { Tile::BORDER_ROUND_SWE_BOLD,  { 14, 6 } },
        { Tile::BORDER_ROUND_NWE_BOLD,  { 15, 7 } },
        { Tile::BORDER_ROUND_NSWE_BOLD, { 15, 8 } },
        { Tile::BORDER_ROUND_NONE_BOLD, { 14, 8 } },
    
        { Tile::PUNCT_SPACE, { 12, 1 } },
        { Tile::PUNCT_FSTOP, { 10, 4 } },
        { Tile::PUNCT_COMMA, { 11, 4 } },
        { Tile::PUNCT_LQUOT, { 12, 4 } },
        { Tile::PUNCT_RQUOT, { 13, 4 } },
        { Tile::PUNCT_EMARK, { 14, 4 } },
        { Tile::PUNCT_QMARK, { 15, 4 } },
    
        { Tile::PUNCT_ELLIPSIS,  {  0, 5 } },
        { Tile::PUNCT_COLON,     {  1, 5 } },
        { Tile::PUNCT_LPAREN,    {  2, 5 } },
        { Tile::PUNCT_RPAREN,    {  3, 5 } },
        { Tile::PUNCT_EEEMARK,   {  4, 5 } },
        { Tile::PUNCT_EQMARK,    {  5, 5 } },
        { Tile::PUNCT_PLUS ,     {  6, 5 } },
        { Tile::PUNCT_MINUS,     {  7, 5 } },
        { Tile::PUNCT_DIVIDE,    {  8, 5 } },
        { Tile::PUNCT_MULTIPLY,  {  9, 5 } },
        { Tile::PUNCT_LTSIGN,    { 10, 5 } },
        { Tile::PUNCT_GTSIGN,    { 11, 5 } },
        { Tile::PUNCT_SOLIDUS,   { 12, 5 } },
        { Tile::PUNCT_MULTSMALL, { 13, 5 } },
    
        { Tile::MENU_CURSOR_SELECTED,   { 14, 5 } },
        { Tile::MENU_CURSOR_UNSELECTED, { 11, 4 } },
        { Tile::PLAIN_FILL, { 15, 5 } },
        
        { Tile::ALPHANUM_A, {  0, 0 } },
        { Tile::ALPHANUM_B, {  1, 0 } },
        { Tile::ALPHANUM_C, {  2, 0 } },
        { Tile::ALPHANUM_D, {  3, 0 } },
        { Tile::ALPHANUM_E, {  4, 0 } },
        { Tile::ALPHANUM_F, {  5, 0 } },
        { Tile::ALPHANUM_G, {  6, 0 } },
        { Tile::ALPHANUM_H, {  7, 0 } },
        { Tile::ALPHANUM_I, {  8, 0 } },
        { Tile::ALPHANUM_J, {  9, 0 } },
        { Tile::ALPHANUM_K, { 10, 0 } },
        { Tile::ALPHANUM_L, { 11, 0 } },
        { Tile::ALPHANUM_M, { 12, 0 } },
        { Tile::ALPHANUM_N, { 13, 0 } },
        { Tile::ALPHANUM_O, { 14, 0 } },
        { Tile::ALPHANUM_P, { 15, 0 } },
        { Tile::ALPHANUM_Q, {  0, 1 } },
        { Tile::ALPHANUM_R, {  1, 1 } },
        { Tile::ALPHANUM_S, {  2, 1 } },
        { Tile::ALPHANUM_T, {  3, 1 } },
        { Tile::ALPHANUM_U, {  4, 1 } },
        { Tile::ALPHANUM_V, {  5, 1 } },
        { Tile::ALPHANUM_W, {  6, 1 } },
        { Tile::ALPHANUM_X, {  7, 1 } },
        { Tile::ALPHANUM_Y, {  8, 1 } },
        { Tile::ALPHANUM_Z, {  9, 1 } },
    
        { Tile::ALPHANUM_A_BOLD, {  0, 2 } },
        { Tile::ALPHANUM_B_BOLD, {  1, 2 } },
        { Tile::ALPHANUM_C_BOLD, {  2, 2 } },
        { Tile::ALPHANUM_D_BOLD, {  3, 2 } },
        { Tile::ALPHANUM_E_BOLD, {  4, 2 } },
        { Tile::ALPHANUM_F_BOLD, {  5, 2 } },
        { Tile::ALPHANUM_G_BOLD, {  6, 2 } },
        { Tile::ALPHANUM_H_BOLD, {  7, 2 } },
        { Tile::ALPHANUM_I_BOLD, {  8, 2 } },
        { Tile::ALPHANUM_J_BOLD, {  9, 2 } },
        { Tile::ALPHANUM_K_BOLD, { 10, 2 } },
        { Tile::ALPHANUM_L_BOLD, { 11, 2 } },
        { Tile::ALPHANUM_M_BOLD, { 12, 2 } },
        { Tile::ALPHANUM_N_BOLD, { 13, 2 } },
        { Tile::ALPHANUM_O_BOLD, { 14, 2 } },
        { Tile::ALPHANUM_P_BOLD, { 15, 2 } },
        { Tile::ALPHANUM_Q_BOLD, {  0, 3 } },
        { Tile::ALPHANUM_R_BOLD, {  1, 3 } },
        { Tile::ALPHANUM_S_BOLD, {  2, 3 } },
        { Tile::ALPHANUM_T_BOLD, {  3, 3 } },
        { Tile::ALPHANUM_U_BOLD, {  4, 3 } },
        { Tile::ALPHANUM_V_BOLD, {  5, 3 } },
        { Tile::ALPHANUM_W_BOLD, {  6, 3 } },
        { Tile::ALPHANUM_X_BOLD, {  7, 3 } },
        { Tile::ALPHANUM_Y_BOLD, {  8, 3 } },
        { Tile::ALPHANUM_Z_BOLD, {  9, 3 } },
        
        { Tile::PUNCT_MONEY,      { 10, 1 } },
        { Tile::PUNCT_MONEY_BOLD, { 10, 3 } },
        
        { Tile::ALPHANUM_0, { 0, 4 } },
        { Tile::ALPHANUM_1, { 1, 4 } },
        { Tile::ALPHANUM_2, { 2, 4 } },
        { Tile::ALPHANUM_3, { 3, 4 } },
        { Tile::ALPHANUM_4, { 4, 4 } },
        { Tile::ALPHANUM_5, { 5, 4 } },
        { Tile::ALPHANUM_6, { 6, 4 } },
        { Tile::ALPHANUM_7, { 7, 4 } },
        { Tile::ALPHANUM_8, { 8, 4 } },
        { Tile::ALPHANUM_9, { 9, 4 } }
    };
    return &texture_map;
}


Palette *Mappings::default_palette() {
    static Palette palette = {
        { PaletteColor::BG_1, { 0x60, 0x60, 0x60 } },
        { PaletteColor::BG_2, { 0x35, 0x97, 0x68 } },
        { PaletteColor::FG_1, { 0xA7, 0xD4, 0x6F } },
        { PaletteColor::FG_2, { 0xFF, 0xED, 0x8F } }
    };
    
    return &palette;
}